Update PlayerHealthBar.cs
вроде как исправил ошибку: Assets\Resources\Scripts\UI_Scripts\PlayerHealthBar.cs(14,49): error CS0246: The type or namespace name 'PlayerCN' could not be found (are you missing a using directive or an assembly reference?)